#!/bin/bash
#cd "${0%/*}" || exit                                # Run from this directory
source /usr/lib/openfoam/openfoam2012/etc/bashrc
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

rm -rf VTK
rm -rf constant/cellToRegion
rm -rf constant/*/polyMesh  # region meshes
rm -r processor*

#------------------------------------------------------------------------------
