#!/bin/bash
#cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

postProcess -func lineSamples -region outBox
gnuplot plotFile.gpi

#------------------------------------------------------------------------------
