#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
source /usr/lib/openfoam/openfoam2012/etc/bashrc

#   cleanCase   ---------------------------------------------------------------
./Allclean
#   runCase     ---------------------------------------------------------------

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions


runApplication blockMesh
runApplication topoSet
runApplication createPatch -overwrite
runApplication surfaceFeatureExtract
runApplication snappyHexMesh -overwrite

restore0Dir
runApplication splitMeshRegions -cellZones -overwrite

# Remove fluid fields from solid regions (important for post-processing)
for region in $(foamListRegions solid)
do
    rm -f 0/$region/{nut,alphat,epsilon,k,U,p_rgh}
    rm -f processor*/0/$region/{nut,alphat,epsilon,k,U,p_rgh}
done

for region in $(foamListRegions)
do
    runApplication -s $region changeDictionary -region $region
done

runApplication $(getApplication)

echo
echo "Use paraFoam -touch-all to create files for paraview post-processing"
echo

#------------------------------------------------------------------------------
