#!/bin/bash
#cd "${0%/*}" || exit                                # Run from this directory
./Allclean
source /usr/lib/openfoam/openfoam2012/etc/bashrc

echo "" > caso.foam

blockMesh
topoSet
createPatch -overwrite
surfaceFeatureExtract

decomposePar
mpirun snappyHexMesh -overwrite -parallel

############
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
restore0Dir -processor
###########

mpirun splitMeshRegions -cellZones -overwrite -parallel

# Remove fluid fields from solid regions (important for post-processing)
for region in $(foamListRegions solid)
do
    rm -f 0/$region/{nut,alphat,epsilon,k,U,p_rgh}
    rm -f processor*/0/$region/{nut,alphat,epsilon,k,U,p_rgh}
done
echo "Done removing"
for region in $(foamListRegions)
do
    mpirun changeDictionary -region $region -parallel
done
echo "Done changeDictionary"


# Run on single processor

mpirun chtMultiRegionFoam -parallel
# Reconstruct
for region in $(foamListRegions)
do
        mpirun redistributePar -reconstruct -parallel -region $region
done



echo
echo "Use paraFoam -touch-all to create files for paraview post-processing"
echo

#------------------------------------------------------------------------------
